# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
      - cron: "0 0 */1 * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    - name: Run Update Python Script
      run: |
        python blog-update.py
    - name: Update README.md file
      run: | 
        git pull --rebase || echo "Git pull failed or no changes"
        git add .
        git status
        git config --local user.email "kar2125@naver.com"
        git config --local user.name "kimAeris"
        git commit -m "Updating Blog Posts" || echo "No changes to commit"
        git push || echo "Git push failed"
