name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: "0 0 */1 * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    - name: Run Update Python Script
      run: |
        python blog-update.py ## 실행시킬 .py이름
    - name: Update README.md file
      run: |
        git pull
        git add .
        git diff
        git config --local user.email "kar2125@naver.com"
        git config --local user.name "kimAeris"
        git commit -m "commit Message"
        git push
